basePath: /api
definitions:
  models.User:
    properties:
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: This is a sample top-up system server.
  title: Top Up System API
  version: "1.0"
paths:
  /users:
    get:
      description: Get users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Get users
      tags:
      - users
swagger: "2.0"
